### ISSUE TITLE
handle http Request

### ISSUE THREAD

**Issue by NeeRaj-2401** [Bnyro/Radiofy#1]
Hi, Bnyro hope u are doing well. I was inspired by this project and tried to create something similar by my own in [Reac-Radio](https://github.com/NeeRaj-2401/ReacRadio).

But the issue is some responses contain http url to stream radio hence browser doesn't plays the audio.
can we find any solution for it ?

![image](https://user-images.githubusercontent.com/88180887/228161629-b2b8da7a-6b82-4ebb-b348-1e3f356d251f.png)

on localhost it works good, but after hosting it doesn't plays the audio

**Comment by Bnyro** [comment]
Nothing I could come up with.
What could be done is using an https proxy, however hosting one is probably not an ideal solution.
I'm not sure if the issue can be prevented by some browser settings, but that's the only real way I see.
